# Bonus Challenge 1 - T-test

In statistics, t-test is used to test if two data samples have a significant difference between their means. There are two types of t-test:

* **Student's t-test** (a.k.a. independent or uncorrelated t-test). This type of t-test is to compare the samples of **two independent populations** (e.g. test scores of students in two different classes). `scipy` provides the [`ttest_ind`](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.ttest_ind.html) method to conduct student's t-test.

* **Paired t-test** (a.k.a. dependent or correlated t-test). This type of t-test is to compare the samples of **the same population** (e.g. scores of different tests of students in the same class). `scipy` provides the [`ttest_re`](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.ttest_rel.html) method to conduct paired t-test.

Both types of t-tests return a number which is called the **p-value**. If p-value is below 0.05, we can confidently declare the null-hypothesis is rejected and the difference is significant. If p-value is between 0.05 and 0.1, we may also declare the null-hypothesis is rejected but we are not highly confident. If p-value is above 0.1 we do not reject the null-hypothesis.

Read more about the t-test in [this article](http://b.link/test50) and [this Quora](http://b.link/unpaired97). Make sure you understand when to use which type of t-test.

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import scipy.stats as ss
from scipy.stats import ttest_ind

#### Import dataset

In this challenge we will work on the Pokemon dataset you have already used. The goal is to test whether different groups of pokemon (e.g. Legendary vs Normal, Generation 1 vs 2, single-type vs dual-type) have different stats (e.g. HP, Attack, Defense, etc.). Use Ironhack's database to load the data (db: pokemon, table: pokemon_stats).

In [2]:
# Your code here:
pokemon=pd.read_csv('/Users/dehilinesma/Downloads/Lab_7_Hypothesis-Testing/Pokemon.csv')
pokemon.set_index('#', inplace=True )
pokemon.head()

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

#### First we want to define a function with which we can test the means of a feature set of two samples. 

In the next cell you'll see the annotations of the Python function that explains what this function does and its arguments and returned value. This type of annotation is called **docstring** which is a convention used among Python developers. The docstring convention allows developers to write consistent tech documentations for their codes so that others can read. It also allows some websites to automatically parse the docstrings and display user-friendly documentations.

Follow the specifications of the docstring and complete the function.

In [3]:
def t_test_features(s1, s2, features=['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Total']):
    """Test means of a feature set of two samples
    
    Args:
        s1 (dataframe): sample 1
        s2 (dataframe): sample 2
        features (list): an array of features to test
    
    Returns:
        dict: a dictionary of t-test scores for each feature where the feature name is the key and the p-value is the value
    """
    results = {    }
    for feature in features :
        results[feature]=ttest_ind(s1[feature],s2[feature]).pvalue

    # Your code here
    
    return results

In [4]:
sample_1=pokemon[pokemon['Legendary']==True].sample(10)
sample_2=pokemon[pokemon['Legendary']==False].sample(10)

In [5]:
sample_2

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
156,Quilava,Fire,NaN,405,58,64,58,80,65,80,2,False
248,Tyranitar,Rock,Dark,600,100,134,110,95,100,61,2,False
711,GourgeistAverage Size,Ghost,Grass,494,65,90,122,58,75,84,6,False
396,Starly,Normal,Flying,245,40,55,30,30,30,60,4,False
684,Swirlix,Fairy,NaN,341,62,48,66,59,57,49,6,False
86,Seel,Water,NaN,325,65,45,55,45,70,45,1,False
79,Slowpoke,Water,Psychic,315,90,65,65,40,40,15,1,False
630,Mandibuzz,Dark,Flying,510,110,65,105,55,95,80,5,False
230,Kingdra,Water,Dragon,540,75,95,95,95,95,85,2,False
280,Ralts,Psychic,Fairy,198,28,25,25,45,35,40,3,False

#### Using the `t_test_features` function, conduct t-test for Lengendary vs non-Legendary pokemons.

*Hint: your output should look like below:*

```
{'HP': 1.0026911708035284e-13,
 'Attack': 2.520372449236646e-16,
 'Defense': 4.8269984949193316e-11,
 'Sp. Atk': 1.5514614112239812e-21,
 'Sp. Def': 2.2949327864052826e-15,
 'Speed': 1.049016311882451e-18,
 'Total': 9.357954335957446e-47}
 ```

In [6]:
# Your code here
t_test_features(sample_1,sample_2,features=['HP','Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Total'])

{'HP': 0.16417616149618464,
 'Attack': 0.0028697261615251426,
 'Defense': 0.06311393031847021,
 'Sp. Atk': 0.00040649434548076306,
 'Sp. Def': 0.002787849693300882,
 'Speed': 0.014809206507183963,
 'Total': 0.0001174040775402136}

#### From the test results above, what conclusion can you make? Do Legendary and non-Legendary pokemons have significantly different stats on each feature?

In [ ]:
# Since we have low significance we can say that our H0 hypothesis is rejected in other words, legendary pokemons are different from non legendary features wise.

#### Next, conduct t-test for Generation 1 and Generation 2 pokemons.

In [7]:
# Your code here
pokemon['Type 2']=pokemon['Type 2'].replace(np.nan,0)
pokemon['type_type']=np.where(pokemon['Type 2']==0,1,2)
pokemon

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,type_type
#,,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,2
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,2
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,2
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,2
4,Charmander,Fire,0,309,39,52,43,60,50,65,1,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,2
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,2
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,2
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,2
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,2

In [8]:
sample_3=pokemon[pokemon['Generation']==1].sample(10)
sample_4=pokemon[pokemon['Generation']==2].sample(10)
t_test_features(sample_3,sample_4,features=['HP','Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Total'])

{'HP': 0.6107674322337602,
 'Attack': 0.252912828576646,
 'Defense': 0.03042862283066226,
 'Sp. Atk': 0.7733605034834242,
 'Sp. Def': 0.7768522495589758,
 'Speed': 0.4694036770507183,
 'Total': 0.6380587887873647}

#### What conclusions can you make?

In [ ]:
# #

#### Compare pokemons who have single type vs those having two types.

In [9]:
# Your code here
sample_5=pokemon[pokemon['type_type']==1].sample(10)
sample_6=pokemon[pokemon['type_type']==2].sample(10)
t_test_features(sample_3,sample_4,features=['HP','Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Total'])

{'HP': 0.6107674322337602,
 'Attack': 0.252912828576646,
 'Defense': 0.03042862283066226,
 'Sp. Atk': 0.7733605034834242,
 'Sp. Def': 0.7768522495589758,
 'Speed': 0.4694036770507183,
 'Total': 0.6380587887873647}

#### What conclusions can you make?

In [ ]:
# p value feature by feature except defense is higher than confidence interval therefore we accept oour H0: in other words there is no difference whether pokemon has 1 or 2 types

#### Now, we want to compare whether there are significant differences of `Attack` vs `Defense`  and  `Sp. Atk` vs `Sp. Def` of all pokemons. Please write your code below.

*Hint: are you comparing different populations or the same population?*

In [10]:
# Your code here
sample7=pokemon['Attack'].sample(10)
sample87=pokemon['Defense'].sample(10)

In [11]:
sample7

#
147     64
325     25
564     78
440      5
401     25
373    145
702     58
531     60
306    140
43      50
Name: Attack, dtype: int64

In [12]:
from scipy.stats import ttest_rel

In [13]:
x=ttest_rel(pokemon['Attack'],pokemon['Defense']).pvalue
print("{:.6f}".format(x))

0.000017

In [14]:
x=ttest_rel(pokemon['Sp. Atk'],pokemon['Sp. Def']).pvalue
print("{:.6f}".format(x))

0.393369

#### What conclusions can you make?

In [ ]:
# Your comment here
#attack defense reject the H0 hypothesis SP.Atk vs SP.Def accept